name: "Test"

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '.github/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '.github/**'

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Test build
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --amd64 \
            --aarch64 \
            --target . \
            --docker-hub apopoutsis